### ISSUE TITLE
Midi source

### ISSUE THREAD

**Issue by Larbino1** [HackerPoet/Composer#1]
Hi! I loved your video. It's criminal that it doesn't have more views.

I was wondering where you sourced you midi files? I can understand you not wanting to include them, but could do with a pointer.

**Comment by HackerPoet** [comment]
The majority of songs came form:

**Ninsheetmusic:**
[https://www.ninsheetmusic.org/](https://www.ninsheetmusic.org/)

**VGMusic (Piano Only):**
[https://www.vgmusic.com/music/other/miscellaneous/piano/](https://www.vgmusic.com/music/other/miscellaneous/piano/)

The is no way to download them all at once, so you need to either download them individually or write a scraper.

**Comment by Larbino1** [comment]
Thank you for the reply

**Comment by AlexPoulsen** [comment]
[https://github.com/AlexPoulsen/vgmusic_midi_scraper](https://github.com/AlexPoulsen/vgmusic_midi_scraper) I wrote a vgmusic scraper if anyone wants to use it.

I'm working on a ninsheetmusic scraper at the moment.

**Comment by AlexPoulsen** [comment]
I'm planning on retraining it on all the vgmusic files as well as using the circle of fifths in the training.
mostly because I couldn't get wine to run it and if I'm gonna retrain it I might as well modify it

**Comment by AlexPoulsen** [comment]
[https://github.com/AlexPoulsen/ninsheetmusic_scraper](https://github.com/AlexPoulsen/ninsheetmusic_scraper) ninsheetmusic scraper is done

**Comment by Markel** [comment]
Thank you @AlexPoulsen !!!
