### ISSUE TITLE
How do I save model/continue training?

### ISSUE THREAD

**Issue by ghost** [HackerPoet/Composer#23]
I don't know if this is normal, but my model building takes more than an hour and takes around 3 hours to get the model.h5. Is it possible to save the training progress and continue it later on?

**Comment by HackerPoet** [comment]
Yes, in `train.py` there should be a flag `CONTINUE_TRAIN` near the top that you can set to `True`.

**Comment by ghost** [comment]
Ahh thank you. Should've checked the code before opening an issue. It worked great btw. Thanks for sharing your code. Keep up your good work! Thanks
