### ISSUE TITLE
Idea: To put numbers on top of the sliders

### ISSUE THREAD

**Issue by JoseLGF** [HackerPoet/Composer#5]
I downloaded your program and I really like it. I even shared it with my friends.
I would really like to be able not only to convert the tunes to wav or mp3, but to recreate them for future use.
My idea is to show/change the value of the sliders with a text label. This way, I can write down the values and use them later, or pass them to a friend, so that he can use them/play with them.
Maybe even copy the values as a text array to the clipboard, so that I can easily save them in a text file.

I think something like this:
![image](https://user-images.githubusercontent.com/33595443/48973177-0a1a6100-efff-11e8-9e78-afed7812a841.png)

**Comment by HackerPoet** [comment]
The slider values are continuous floating point, not integers so it might be a little too crowded to display them like that.  Maybe I can display a little tool-tip next to the slider you're dragging instead?

I can add an import/export option for a text file with the values.  That wouldn't be hard.  I'll do that soon when I have time.

**Comment by HackerPoet** [comment]
Alright, I added the new features.  Press 'S' to save the slider values to a file 'song.txt'.  To load a file, use it as the command-line argument (or just drag it over the executable).

Adding slider text wasn't very useful.  The tick marks are each 1 unit apart already so its pretty easy to just eyeball what the value is.  For exact values, saving the sliders gives you that now.

**Comment by JoseLGF** [comment]
Thank you very much!

I tested the new function and it works great!

**Comment by Fivebee2** [comment]
I am thinking about you doing that to all the other neural networks.
