### ISSUE TITLE
name 'end_ix' is not defined

### ISSUE THREAD

**Issue by MumeiHito** [HackerPoet/Composer#6]
Hello! Tried to compile your code. I compiled load_song.py first - no problems. Then I tried train.py and got 
Traceback (most recent call last):
  File "/Users/dinoz4vrick/PycharmProjects/musicGenerator/train.py", line 118, in <module>
    assert(end_ix == num_samples)
NameError: name 'end_ix' is not defined

**Comment by HackerPoet** [comment]
I see you've already closed this, so I hope that means you resolved the issue.  But it appears that the number of songs or offsets would have to be 0 for this to happen.

**Comment by denevik** [comment]
@DZ4VR In case that you solve the issue, could you please put a comment on it to let everyone the solution? Thanks
By the way @HackerPoet  could you please help me figure out following issue:
`python load_songs.py 
Loading Songs...
ERROR  Music\sum41_fat_lip.mid
ERROR  Music\rivereminemgc9.mid
Saving 0 samples...
Done`
How can I solve that? Thank you
