### ISSUE TITLE
Can't load music

### ISSUE THREAD

**Issue by MumeiHito** [HackerPoet/Composer#7]
So I tried to run load_songs.py and got:
ERROR  /Users/dinoz4vrick/music_for_nn/DemonCastlePinnacle.mid
ERROR  /Users/dinoz4vrick/music_for_nn/Ff7-Jenova_Absolute.mid
ERROR  /Users/dinoz4vrick/music_for_nn/Gestation.mid
ERROR  /Users/dinoz4vrick/music_for_nn/CastlevaniaLevel1AS.mid
ERROR  /Users/dinoz4vrick/music_for_nn/BKendsolo.mid
ERROR  /Users/dinoz4vrick/music_for_nn/ahead_on_our_way_piano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/Z8.mid
ERROR  /Users/dinoz4vrick/music_for_nn/trailblood.mid
ERROR  /Users/dinoz4vrick/music_for_nn/cpt_clawswamp.mid
  ^^^^^^ WARNING ^^^^^^
    /Users/dinoz4vrick/music_for_nn/BanjoTooie.mid
    Detected multiple distinct time signatures.
  ^^^^^^ WARNING ^^^^^^
[]
ERROR  /Users/dinoz4vrick/music_for_nn/DOS.mid
ERROR  /Users/dinoz4vrick/music_for_nn/FF3_Battle_(Piano).mid
ERROR  /Users/dinoz4vrick/music_for_nn/circus_charlie_1_4.mid
ERROR  /Users/dinoz4vrick/music_for_nn/Cohens_Masterpiece.mid
ERROR  /Users/dinoz4vrick/music_for_nn/Suteki_Da_Ne_(Piano_Version).mid
ERROR  /Users/dinoz4vrick/music_for_nn/caitsith.mid
  ^^^^^^ WARNING ^^^^^^
    /Users/dinoz4vrick/music_for_nn/At_Zanarkand_Piano_Collection_(Unofficial).mid
    Detected multiple distinct time signatures.
  ^^^^^^ WARNING ^^^^^^
[]
ERROR  /Users/dinoz4vrick/music_for_nn/n64_f0x_sm01_piano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/edc.mid
ERROR  /Users/dinoz4vrick/music_for_nn/Oppressed.mid
ERROR  /Users/dinoz4vrick/music_for_nn/ff4-airship.mid
  ^^^^^^ WARNING ^^^^^^
    /Users/dinoz4vrick/music_for_nn/magustheme-piano.mid
    Detected multiple distinct time signatures.
  ^^^^^^ WARNING ^^^^^^
[]
ERROR  /Users/dinoz4vrick/music_for_nn/ff7themep.mid
ERROR  /Users/dinoz4vrick/music_for_nn/faxoverworld.mid
ERROR  /Users/dinoz4vrick/music_for_nn/FFVII_BATTLE.mid
ERROR  /Users/dinoz4vrick/music_for_nn/electric_de_chocobo.mid
ERROR  /Users/dinoz4vrick/music_for_nn/dkcddtBADparade.mid
  ^^^^^^ WARNING ^^^^^^
    /Users/dinoz4vrick/music_for_nn/Aion_Tower_Of_Eternity.mid
    Detected multiple distinct time signatures.
  ^^^^^^ WARNING ^^^^^^
[]
ERROR  /Users/dinoz4vrick/music_for_nn/dk_title.mid
  ^^^^^^ WARNING ^^^^^^
    /Users/dinoz4vrick/music_for_nn/Ff7-One_Winged.mid
    Detected multiple distinct time signatures.
  ^^^^^^ WARNING ^^^^^^
[]
ERROR  /Users/dinoz4vrick/music_for_nn/norKEM.mid
ERROR  /Users/dinoz4vrick/music_for_nn/AsaZanarkand.mid
ERROR  /Users/dinoz4vrick/music_for_nn/dino_riki_1.mid
ERROR  /Users/dinoz4vrick/music_for_nn/N-Gin.mid
ERROR  /Users/dinoz4vrick/music_for_nn/dkl-bosssolo.mid
ERROR  /Users/dinoz4vrick/music_for_nn/Finalfantasy5gilgameshp.mid
ERROR  /Users/dinoz4vrick/music_for_nn/byakuyagensoutanPIANO.mid
ERROR  /Users/dinoz4vrick/music_for_nn/CKFF6DBp.mid
ERROR  /Users/dinoz4vrick/music_for_nn/DKONG.mid
ERROR  /Users/dinoz4vrick/music_for_nn/Cids.mid
ERROR  /Users/dinoz4vrick/music_for_nn/lurk_in_dark.mid
ERROR  /Users/dinoz4vrick/music_for_nn/Motzhand_Quickie.mid
ERROR  /Users/dinoz4vrick/music_for_nn/dkl-constructsolo.mid
ERROR  /Users/dinoz4vrick/music_for_nn/dkcddt-wrinkle64SOLO.mid
ERROR  /Users/dinoz4vrick/music_for_nn/4_-_3_Magic_Hearts.mid
ERROR  /Users/dinoz4vrick/music_for_nn/corridor.mid
  ^^^^^^ WARNING ^^^^^^
    /Users/dinoz4vrick/music_for_nn/3_-_Athene_Sonata.mid
    Detected multiple distinct time signatures.
  ^^^^^^ WARNING ^^^^^^
[]
  ^^^^^^ WARNING ^^^^^^
    /Users/dinoz4vrick/music_for_nn/FFX_-_Ending_Theme_(Piano_Version)_-_by_Angel_FF.mid
    Detected multiple distinct time signatures.
  ^^^^^^ WARNING ^^^^^^
[]
  ^^^^^^ WARNING ^^^^^^
    /Users/dinoz4vrick/music_for_nn/ff4pclov.mid
    Detected multiple distinct time signatures.
  ^^^^^^ WARNING ^^^^^^
[]
ERROR  /Users/dinoz4vrick/music_for_nn/AT.mid
ERROR  /Users/dinoz4vrick/music_for_nn/Final_Fantasy_7_-_Judgement_Day_Piano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/sobf.mid
ERROR  /Users/dinoz4vrick/music_for_nn/In_Zanarkand.mid
ERROR  /Users/dinoz4vrick/music_for_nn/ff2japantown.mid
ERROR  /Users/dinoz4vrick/music_for_nn/waltz_de_choco.mid
ERROR  /Users/dinoz4vrick/music_for_nn/z_aeristhemepiano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/6_-_Orpheus'_Journey.mid
ERROR  /Users/dinoz4vrick/music_for_nn/BK_FP_Piano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/ff4pcpro.mid
ERROR  /Users/dinoz4vrick/music_for_nn/dkcddtjanglebesolo.mid
  ^^^^^^ WARNING ^^^^^^
    /Users/dinoz4vrick/music_for_nn/act_raiser-north_wall.mid
    Detected multiple distinct time signatures.
  ^^^^^^ WARNING ^^^^^^
[]
ERROR  /Users/dinoz4vrick/music_for_nn/Z23.mid
ERROR  /Users/dinoz4vrick/music_for_nn/Final_Fantasy_Matouyas_Cave_Piano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/continue.mid
  ^^^^^^ WARNING ^^^^^^
    /Users/dinoz4vrick/music_for_nn/redwings.mid
    Detected multiple distinct time signatures.
  ^^^^^^ WARNING ^^^^^^
[]
ERROR  /Users/dinoz4vrick/music_for_nn/2_-_A_brave_Warrior.mid
ERROR  /Users/dinoz4vrick/music_for_nn/ff4_piano_collections-main_theme.mid
ERROR  /Users/dinoz4vrick/music_for_nn/dkl-blimpsolo.mid
ERROR  /Users/dinoz4vrick/music_for_nn/BT_Character_Parade_Piano.mid
  ^^^^^^ WARNING ^^^^^^
    /Users/dinoz4vrick/music_for_nn/silentlight-piano.mid
    Detected multiple distinct time signatures.
  ^^^^^^ WARNING ^^^^^^
[]
ERROR  /Users/dinoz4vrick/music_for_nn/Rachel_piano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/dkcddtwrinklesolo.mid
ERROR  /Users/dinoz4vrick/music_for_nn/wings.mid
ERROR  /Users/dinoz4vrick/music_for_nn/Here_comes_trouble_piano_V2.mid
ERROR  /Users/dinoz4vrick/music_for_nn/Z-Infinity--.mid
ERROR  /Users/dinoz4vrick/music_for_nn/dayafter.mid
ERROR  /Users/dinoz4vrick/music_for_nn/FF6epitaph_piano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/BT_Witchyworld_Piano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/B-K_RBBAquatic_Piano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/DKCDKQ-bayousolo.mid
ERROR  /Users/dinoz4vrick/music_for_nn/Animania.mid
ERROR  /Users/dinoz4vrick/music_for_nn/dkl.mid
ERROR  /Users/dinoz4vrick/music_for_nn/BT_Spiral_Mountain_Piano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/EAGLE.mid
ERROR  /Users/dinoz4vrick/music_for_nn/dkcddt-ccalypsolo.mid
ERROR  /Users/dinoz4vrick/music_for_nn/FFIII_Edgar_And_Sabin_Piano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/ultros.mid
ERROR  /Users/dinoz4vrick/music_for_nn/ff1deadp.mid
ERROR  /Users/dinoz4vrick/music_for_nn/Z9-2.mid
ERROR  /Users/dinoz4vrick/music_for_nn/CVAoS-Heart_of_Fire-piano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/GV.mid
ERROR  /Users/dinoz4vrick/music_for_nn/BlueStone_LastDungeon.mid
ERROR  /Users/dinoz4vrick/music_for_nn/BT_Dragon_Bosses_Piano_100.mid
  ^^^^^^ WARNING ^^^^^^
    /Users/dinoz4vrick/music_for_nn/BanjoKazooie.mid
    Detected multiple distinct time signatures.
  ^^^^^^ WARNING ^^^^^^
[]
ERROR  /Users/dinoz4vrick/music_for_nn/BaldursGate-Safe_in_Beregost.mid
ERROR  /Users/dinoz4vrick/music_for_nn/secretotforest-piano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/cearleonpiano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/DKC_Map2.mid
ERROR  /Users/dinoz4vrick/music_for_nn/cchitcat.mid
ERROR  /Users/dinoz4vrick/music_for_nn/BKigloosolo.mid
ERROR  /Users/dinoz4vrick/music_for_nn/athena_lvl_2.mid
  ^^^^^^ WARNING ^^^^^^
    /Users/dinoz4vrick/music_for_nn/Aion_Death_Waltz.mid
    Detected multiple distinct time signatures.
  ^^^^^^ WARNING ^^^^^^
[]
ERROR  /Users/dinoz4vrick/music_for_nn/DKCDKQ-lavasolo.mid
ERROR  /Users/dinoz4vrick/music_for_nn/mumbofixed.mid
ERROR  /Users/dinoz4vrick/music_for_nn/rufus.mid
ERROR  /Users/dinoz4vrick/music_for_nn/mkingdom.mid
ERROR  /Users/dinoz4vrick/music_for_nn/IsleOHags_Cauldron_Keep_Piano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/ff4-fight1.mid
ERROR  /Users/dinoz4vrick/music_for_nn/Life_Stream.mid
ERROR  /Users/dinoz4vrick/music_for_nn/ebsnowschool.mid
ERROR  /Users/dinoz4vrick/music_for_nn/FP.mid
ERROR  /Users/dinoz4vrick/music_for_nn/DDRSo_Deep_Piano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/columns-clothos-midi.mid
ERROR  /Users/dinoz4vrick/music_for_nn/JENOVA.mid
ERROR  /Users/dinoz4vrick/music_for_nn/LostPaintingPiano.mid
ERROR  /Users/dinoz4vrick/music_for_nn/thenightmarebegins.mid
  ^^^^^^ WARNING ^^^^^^
    /Users/dinoz4vrick/music_for_nn/FF4.mid
    Detected multiple distinct time signatures.
  ^^^^^^ WARNING ^^^^^^

Saving 0 samples...
How do I fix it? I downloaded some sources from https://www.vgmusic.com/music/other/miscellaneous/piano/

I did not edit file, just changed dirs = ["/Users/dinoz4vrick/music_for_nn"] 
(my os is macos)

**Comment by MumeiHito** [comment]
Is there are some functions which are specially for python2?

**Comment by HackerPoet** [comment]
Ah yes, you would have to replace all the divisions '/' with truncated divisions '//'

**Comment by aletote** [comment]
I have the same problem, changing / for // doesn't solve it.
